-- ============================================================================
-- AM SRI PETSHOP — Supabase schema
-- Run once in: Supabase Dashboard → SQL Editor → New query → paste → Run
--
-- Mirrors the app's current data model (data/*.json + server.js):
--   products, orders (items as JSON), contact_messages, promo_codes
-- All column names are snake_case; map to/from the app's camelCase in code.
-- ============================================================================

-- ⚠️ Drop-and-recreate makes this script re-runnable on a fresh project.
--    Running it on a database that already has data will DELETE that data.
drop table if exists public.orders cascade;
drop table if exists public.products cascade;
drop table if exists public.contact_messages cascade;
drop table if exists public.promo_codes cascade;

-- ── PRODUCTS ────────────────────────────────────────────────────────────────
-- "generated by default" allows importing existing numeric IDs (1, 2, 3...)
-- while still auto-generating IDs for new rows.
create table public.products (
    id          bigint generated by default as identity primary key,
    name        text           not null,
    category    text           not null default 'accessories',
    price       numeric(10,2)  not null check (price >= 0),
    stock       integer        not null default 0 check (stock >= 0),
    description text           not null default '',
    image       text           not null default '/images/logo.jpeg',
    archived    boolean        not null default false,
    created_at  timestamptz    not null default now(),
    updated_at  timestamptz    not null default now()
);

create index products_category_idx on public.products (category);
create index products_archived_idx on public.products (archived) where archived = false;

-- Keep updated_at fresh automatically
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger products_set_updated_at
    before update on public.products
    for each row execute function public.set_updated_at();

-- ── ORDERS ──────────────────────────────────────────────────────────────────
-- order_id is the app-generated human code (e.g. "AMSMTMP4Y27EC0D48").
-- items / address / payment_details / billing_address stay JSONB to match
-- the existing order payload 1:1 and keep checkout logic unchanged.
create table public.orders (
    order_id                 text          primary key,
    customer_name            text          not null,
    customer_email           text          not null,
    customer_phone           text          not null,
    shipping_address         text,
    address                  jsonb,
    items                    jsonb         not null default '[]'::jsonb,
    subtotal                 numeric(10,2) not null default 0 check (subtotal >= 0),
    shipping                 numeric(10,2) not null default 0 check (shipping >= 0),
    tax                      numeric(10,2) not null default 0 check (tax >= 0),
    discount                 numeric(10,2) not null default 0 check (discount >= 0),
    promo_code               text,
    total                    numeric(10,2) not null default 0 check (total >= 0),
    payment_method           text,
    payment_details          jsonb,
    billing_same_as_shipping boolean       not null default true,
    billing_address          jsonb,
    payment_status           text          not null default 'pending',
    delivery_method          text          not null default 'standard',
    status                   text          not null default 'pending'
        check (status in ('pending','processing','shipped','delivered','cancelled')),
    tracking_number          text,
    estimated_delivery       timestamptz,
    created_at               timestamptz   not null default now()
);

create index orders_created_at_idx on public.orders (created_at desc);
create index orders_status_idx     on public.orders (status);

-- ── CONTACT MESSAGES ────────────────────────────────────────────────────────
create table public.contact_messages (
    id         text        primary key default (gen_random_uuid())::text,
    name       text        not null,
    phone      text        not null,
    email      text        not null,
    subject    text        not null,
    message    text        not null,
    created_at timestamptz not null default now()
);

create index contact_messages_created_at_idx on public.contact_messages (created_at desc);

-- ── PROMO CODES ─────────────────────────────────────────────────────────────
create table public.promo_codes (
    code         text          primary key,
    type         text          not null check (type in ('percent','flat')),
    value        numeric(10,2) not null check (value >= 0),
    min_subtotal numeric(10,2) not null default 0 check (min_subtotal >= 0),
    max_discount numeric(10,2) not null default 0 check (max_discount >= 0),
    description  text          not null default '',
    active       boolean       not null default true
);

-- Seed the four codes currently defined in data/promo-codes.js
insert into public.promo_codes (code, type, value, min_subtotal, max_discount, description, active) values
    ('PETLOVE10',  'percent',  10,  0,    500,  '10% off your order (max ₹500)',                   true),
    ('WELCOME150', 'flat',     150, 999,  150,  '₹150 off orders above ₹999',                      true),
    ('AQUA20',     'percent',  20,  2000, 1000, '20% off aquarium orders above ₹2000 (max ₹1000)', true),
    ('FREESHIP',   'flat',     49,  500,  49,   'Free shipping on orders above ₹500',              true);

-- ── ROW LEVEL SECURITY ──────────────────────────────────────────────────────
-- The Express server will use the SECRET key, which bypasses RLS entirely.
-- These policies only govern direct client-side (publishable key) access.

alter table public.products         enable row level security;
alter table public.orders           enable row level security;
alter table public.contact_messages enable row level security;
alter table public.promo_codes      enable row level security;

-- Anyone can browse non-archived products (shop + product pages)
create policy "Public read active products"
    on public.products for select
    using (archived = false);

-- Anyone can read active promo codes (checkout coupon validation)
create policy "Public read active promo codes"
    on public.promo_codes for select
    using (active = true);

-- Anyone can submit a contact message; reading them stays server-only
create policy "Anyone can submit contact message"
    on public.contact_messages for insert
    with check (true);

-- Orders: NO public policies. Anonymous users cannot read other people's
-- orders, and cannot create/modify them directly. All order reads/writes go
-- through your server (secret key). If you later move checkout fully
-- client-side, add e.g.:
--   create policy "Anyone can create an order"
--       on public.orders for insert with check (true);

-- ── REALTIME (optional, replaces the current SSE setup later) ───────────────
-- Lets clients subscribe to order inserts/updates via Supabase Realtime.
do $$
begin
    alter publication supabase_realtime add table public.orders;
exception
    when duplicate_object then null; -- already added
end $$;
